name: demo
on: 
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  test-code:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install requirements
        id: install-requirements
        run: pip install -r requirements.txt
      - name: run py test
        run: pytest2 --cov-report html:htmlcov --cov-report term --cov=project tests
      - name: upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: htmlcov/
      - name: install requirements failure msg
        if: failure() && steps.install-requirements.outcome == 'failure'
        run: echo "install requirements failed, please check the requirements.txt file"
  
  deploy:
    runs-on: ubuntu-22.04
    needs: test-code
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: deploy code
        run: echo "deploy........."